import { defineField, defineType } from "sanity";

export const profile = defineType({
  name: "profile",
  title: "Profile",
  type: "document",
  fields: [
    defineField({ name: "name", title: "Full name", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "shortName", title: "Short name", type: "string" }),
    defineField({ name: "role", title: "Professional role line", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "headline", title: "Homepage headline", type: "string", validation: (rule) => rule.required().max(90) }),
    defineField({ name: "introduction", title: "Short introduction", type: "text", rows: 4, validation: (rule) => rule.required().max(260) }),
    defineField({ name: "portrait", title: "Professional portrait", type: "image", options: { hotspot: true } }),
    defineField({ name: "portraitAlt", title: "Portrait description", type: "string", description: "Describe the portrait for visitors using screen readers." }),
    defineField({ name: "cvFile", title: "CV (PDF)", type: "file", options: { accept: "application/pdf" } }),
    defineField({ name: "location", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "email", type: "email", validation: (rule) => rule.required() }),
    defineField({ name: "phone", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "linkedin", title: "LinkedIn URL", type: "url" }),
    defineField({ name: "scholar", title: "Google Scholar URL", type: "url" }),
    defineField({ name: "github", title: "GitHub URL", type: "url" }),
    defineField({ name: "youtube", title: "YouTube URL", type: "url", description: "Optional. Add this when the channel is ready." }),
    defineField({ name: "biography", title: "Biography paragraphs", type: "array", of: [{ type: "text", rows: 5 }], validation: (rule) => rule.required().min(1) }),
    defineField({
      name: "metrics",
      title: "Homepage profile highlights",
      description: "Up to four compact facts shown beside the Professional Profile.",
      type: "array",
      validation: (rule) => rule.max(4),
      of: [{ type: "object", fields: [defineField({ name: "value", type: "string", validation: (rule) => rule.required() }), defineField({ name: "label", type: "string", validation: (rule) => rule.required() })] }],
    }),
    defineField({
      name: "education",
      type: "array",
      of: [{ type: "object", fields: [
        defineField({ name: "degree", type: "string", validation: (rule) => rule.required() }),
        defineField({ name: "institution", type: "string", validation: (rule) => rule.required() }),
        defineField({ name: "note", type: "text", rows: 2, validation: (rule) => rule.required() }),
        defineField({ name: "cgpa", title: "CGPA (optional)", type: "string", description: "Only enter a verified result. Leave blank to omit it from the website." }),
        defineField({ name: "tgpa", title: "TGPA (optional)", type: "string", description: "Only enter a verified result. Leave blank to omit it from the website." }),
        defineField({ name: "gradeScale", title: "Grade scale (optional)", type: "string", description: "For example, 4.00. Shown only when CGPA or TGPA is entered." }),
        defineField({ name: "relevantCourses", title: "Relevant courses", type: "array", of: [{ type: "string" }], options: { layout: "tags" }, description: "Optional. Add actual courses from this degree; leave empty until confirmed." }),
      ] }],
      validation: (rule) => rule.required().min(1),
    }),
  ],
  preview: { select: { title: "name", subtitle: "role", media: "portrait" } },
});
